name: 'Ocean Sail command'
description: 'Runs the Ocean Sail command for a specific type of integration'
inputs:
  type:
    description: 'The type of the integration to run'
    required: true
  version:
    description: 'The version of the integration to run'
    required: false
    default: 'latest'
  port_client_id:
    description: 'The port client id'
    required: true
  port_client_secret:
    description: 'The port client secret'
    required: true
  initialize_port_resources:
    description: 'Should ocean try to create the default blueprints, pages & integration config for the integration'
    required: false
    default: 'true'
  event_listener_type:
    description: 'The type of the event listener to use'
    required: false
    default: 'ONCE'
  integration_config:
    description: 'Changing configuration between different integration types'
    required: false
    default: '{}'
  additional_env_vars:
    description: 'Additional environment variables to pass to the integration'
    required: false
    default: '{}'

  # Misc inputs
  platform:
    description: 'The platform to run the integration on'
    required: false
    default: 'linux/amd64'
  container_registry:
    description: 'The container registry to pull the image from'
    required: false
    default: 'ghcr.io/port-labs'
outputs:
  exit_code:
    description: 'The exit code of the Ocean Sail command'
    value: ${{ steps.ocean-sail.outputs.exit_code }}
runs:
  using: "composite"
  steps:
    - name: ocean-sail
      run: |
        image_name="ghcr.io/port-labs/port-ocean-${{ inputs.type }}:${{ inputs.version }}"
        
        echo "OCEAN__EVENT_LISTENER={\"type\":\"${{ inputs.event_listener_type }}\"}" >> .env
        echo "OCEAN__INITIALIZE_PORT_RESOURCES=${{ inputs.initialize_port_resources }}" >> .env
        echo "OCEAN__PORT__CLIENT_ID=${{ inputs.port_client_id }}" >> .env
        echo "OCEAN__PORT__CLIENT_SECRET=${{ inputs.port_client_secret }}" >> .env
        
        INTEGRATION_CONFIG=$(echo ${{ inputs.integration_config }} | jq -r 'to_entries[] | "OCEAN__INTEGRATION__CONFIG__\(.key)=\(.value)"')
        for CONFIG in $INTEGRATION_CONFIG; do
            echo $CONFIG >> .env
        done
        
        # Assuming additional_env_vars is a JSON object
        ENV_VARS_JSON="${{ inputs.additional_env_vars }}"
        
        # Convert JSON to a Bash array
        ENV_VARS_ARRAY=($(echo $ENV_VARS_JSON | jq -r 'keys_unsorted[]'))

        # Iterate over the keys
        for KEY in "${ENV_VARS_ARRAY[@]}"; do
          VALUE=$(echo $ENV_VARS_JSON | jq -r ".$KEY")
          echo "$KEY=$VALUE" >> .env
        done
        
        cat .env

        docker run -i --rm --platform=${{ inputs.platform }} --env-file .env $image_name
        
        echo "exit_code=$?" >> $GITHUB_ENV

      shell: bash

    - name: cleanup
      shell: bash
      run: |
        rm .env