name: test
on:
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./sail
        with:
          type: 'jira'
          integration_config: '{"jira_host":"https://jira.com","atlassian_user_email":"jira_username","atlassian_user_token":"jira_password"}'
        # input params if you have any
