name: test
on:
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ./sail
        with:
          type: 'jira'
        env:
          OCEAN__INTEGRATION__CONFIG__JIRA__HOST: 'https://jira.com'
          OCEAN__INTEGRATION__CONFIG__JIRA__ATLASSIAN_USER_EMAIL: 'jira_username'
          OCEAN__INTEGRATION__CONFIG__JIRA__ATLASSIAN_USER_TOKEN: 'jira_password'
        # input params if you have any
