name: test
on:
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ./sail
        with:
          type: 'jira'
          port_client_id: 'port_client_id'
          port_client_secret: 'port_client_secret'
          config: |
            jira_host:'https://jira.com'
            atlassian_user_email:'jira_username'
            atlassian_user_token:'jira_password'